### PR TITLE
Implement MULTILINESTRING, MULTIPOLYGON

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
@skj3gg You know what to do

**Comment by skj3gg** [comment]
You want me to do the thing?

**Comment by frewsxcv** [comment]
I meant, can you review?

**Comment by skj3gg** [comment]
I can so do the thing. Give me five minutes!

**Comment by skj3gg** [comment]
The thing is done :shipit:

**Pull request merged**
