### PR TITLE
Relicense as "MIT/Apache-2.0".

### PR DESCRIPTION
**Pull request by frewsxcv**
I'm the only contributor, so this should be a straightforward license
change.

### CODE REVIEW

**Comment by frewsxcv** [comment]
@aelita-mergebot r+

**Comment by frewsxcv** [comment]
@aelita-mergebot r+

**Comment by notriddle** [comment]
Since you're on a team, you're going to need a publicly-visible reviewers team for this to work right. Sorry 'bout forgetting to document that.

**Comment by frewsxcv** [comment]
@aelita-mergebot r+

**Comment by frewsxcv** [comment]
@aelita-mergebot r+

**Comment by frewsxcv** [comment]
@aelita-mergebot r+

**Pull request merged**
